### ISSUE TITLE
Zooming in deselects Row in Timegraph chart

### ISSUE THREAD

**Issue by muddana-satish** [theia-ide/timeline-chart#50]
After a row and state is selected in timegraph chart, zooming in deselects them. I believe they should be retained.

**Row deselected:**
![Row Select Issue](https://user-images.githubusercontent.com/70230232/94890780-436b5580-044e-11eb-8685-684994c05b4e.gif)

**Actual State deselected:**

![State deselects](https://user-images.githubusercontent.com/70230232/95483077-cc0d5880-095c-11eb-8ab9-f52793f39d1c.gif)

**Comment by tahini** [comment]
Could you detail in which condition you can produce this bug? browser, condition on selected row/state. I cannot reproduce it here.

**Comment by muddana-satish** [comment]
@tahini  I don't think it is dependent on browser. Everytime we call states API, the entire chart is refreshed without retaining the previously selected state and row. One way to reproduce this is to make sure you are zooming in enough so that it calls states API. In the .gif below, the row is deselected everything there is a call to the states API. Let me know if you are still unable to reproduce this issue.

![deselects-row](https://user-images.githubusercontent.com/70230232/94951470-5283ef00-04b2-11eb-999b-62487ec847b1.gif)

**Comment by tahini** [comment]
Ok, I can reproduce this by zooming with the 'w' and 's' keys, not zooming from the navigator.
