### ISSUE TITLE
Ability to select a row using Mouse.

### ISSUE THREAD

**Issue by muddana-satish** [theia-ide/timeline-chart#52]
User should be able to click on a row to select it.

![Select Row](https://user-images.githubusercontent.com/70230232/95403116-58793600-08df-11eb-8155-b48f233f6fbc.gif)

**Comment by muddana-satish** [comment]
@tahini Are you working on fixing this issue or is it open? 
If I remember correctly I tested this with your fork and I saw this feature working fine. (may be I was mistaken) Could you please confirm.

**Comment by tahini** [comment]
No, I'm not working on timeline-chart at all, I just review patches here ;-)

Which fork are you talking about? Maybe it's someone else's (i have a few branches from other people)

**Comment by muddana-satish** [comment]
I cannot recollect it at this moment. Never mind. Thanks for the clarification. I can work on this. :)
