### ISSUE TITLE
Gridlines are not on rounded time boundaries

### ISSUE THREAD

**Issue by PatrickTasse** [theia-ide/timeline-chart#54]
The time graph gridlines and axis ticks are on rounded multiples of the step length away from the start time of the view range.
But the absolute time of the gridline will not be on a rounded number because the time graph does not seem to be aware of the time offset of its view range, which is only known by the (external) implementation of the numberTranslator.

The time offset should be available and used by the time graph so that it can set the gridlines and axis ticks on rounded boundaries.

**Comment by bhufmann** [comment]
Can you  provide a screenshot for illustration purposes?

**Comment by PatrickTasse** [comment]
Fixed with https://github.com/theia-ide/timeline-chart/pull/172
